flashlex:
  app:
    callback: persistent
    thread: subscribe
    message: This is a really basic message.
    db:
      dataPath: /home/pi/projects/flashlex-pi-python/data 
      subscriptionData: subscription.json
      expireSeconds: 3600 #messages older than an hour      
  dist:
    commitSha: 04ef6427b67c5d2a332cdccad72252b992ee0911
  thing:
    name: ecd13b11-yazka
    endpoint: a1khvirpxw0646-ats.iot.us-east-1.amazonaws.com
    keys:
      path: /home/pi/projects/flashlex-pi-python/keys
      rootCA: root-ca-cert.pem
      cert: ecd13b11-yazka-certificate.pem
      privateKey: ecd13b11-yazka-keypair-private.pem
      publicKey: ecd13b11-yazka-keypair-public.pem
    mqtt:
      pubsub:
        topic: pubsub/ecd13b11-yazka
      ingress:
        topic: ingress/ecd13b11-yazka
      egress:
        topic: egress/ecd13b11-yazka 
      useWebsocket: false
      port: 8883
      autoReconnectBackoffTime:
        baseReconnectQuietTimeSecond: 1
        maxReconnectQuietTimeSecond: 360 
        stableConnectionTimeSecond: 60
      offlinePublishQueueing: -1
      drainingFrequency: 2
      connectDisconnectTimeout: 60
      mqttOperationTimeout: 120
